# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 02:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('file', models.ImageField(upload_to='%Y%m%d')),
                ('message', models.CharField(blank=True, max_length=150, null=True)),
                ('task_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['-uploaded', 'name'],
            },
        ),
    ]
